### ISSUE TITLE
Partially signed Tx

### ISSUE THREAD

**Issue by fsodano** [stellar-expert/albedo#53] opened 2021-04-12 13:31 UTC
Hi all,

This is possibly me not understanding how it works, but I'd like to see if there's a workaround.

I am offering the user to sign a transaction that required 3 signatures; 2 signatures are already included and their signature is the third one.

The transaction consists of:

Main signatory account A
Main signatory account B

Issuer Account C (signed w/ main signatory account A)
Distributor Account D (signed w/main signatory account B)
User Account C

User C pays into Distributor Account D (2 payments)
Issuer Account pays into Distributor Account D
Distributor account D pays into User C

I am seeing that "More signatures are required" but the transaction goes through just fine. Is this the expected behaviour?

![image](https://user-images.githubusercontent.com/844181/114401363-3215b980-9be6-11eb-85f1-565bcb6d9525.png)

Here is the test XDR:

https://laboratory.stellar.org/#xdr-viewer?input=AAAAAgAAAABDt6sTdUhUkL%2BzdldE1gNS1NBnLun4K6sDFaOVJ%2BeWEQAAAyAABNboAAAAtwAAAAAAAAAAAAAACAAAAAEAAAAAH4InrCof9y5jJhLJdnhUH5PQUjVjiLwfDUlBxow3gDYAAAAGAAAAAlhUU0FSUwAAAAAAAAAAAAD%2BtBOh28Q8gg%2FXai72CIyzafowHwCf8bqYlAbcJULalAAAD9h0YwkBAAAAAQAAAABDt6sTdUhUkL%2BzdldE1gNS1NBnLun4K6sDFaOVJ%2BeWEQAAAAEAAAAAH4InrCof9y5jJhLJdnhUH5PQUjVjiLwfDUlBxow3gDYAAAACWFRTQVJTAAAAAAAAAAAAAP60E6HbxDyCD9dqLvYIjLNp%2BjAfAJ%2FxupiUBtwlQtqUAAAAAIt5kQAAAAABAAAAAB%2BCJ6wqH%2FcuYyYSyXZ4VB%2BT0FI1Y4i8Hw1JQcaMN4A2AAAABgAAAAJYVFNVU0RDAAAAAAAAAAAAYdNCcD5YFIcLTAcrVlZaeBsOllhsEuhB3f%2BWCpoXVNgAAAAbCwQS1gAAAAEAAAAAQ7erE3VIVJC%2Fs3ZXRNYDUtTQZy7p%2BCurAxWjlSfnlhEAAAABAAAAAB%2BCJ6wqH%2FcuYyYSyXZ4VB%2BT0FI1Y4i8Hw1JQcaMN4A2AAAAAlhUU1VTREMAAAAAAAAAAABh00JwPlgUhwtMBytWVlp4Gw6WWGwS6EHd%2F5YKmhdU2AAAAAAA7gmAAAAAAQAAAAAfgiesKh%2F3LmMmEsl2eFQfk9BSNWOIvB8NSUHGjDeANgAAAAYAAAACWFRBTkxQAAAAAAAAAAAAAH4Xu5kFY4ZsFShIpmVD6qqNNyKhsMVijE2ztm%2BqDb51AAABSzVIRuwAAAABAAAAAH4Xu5kFY4ZsFShIpmVD6qqNNyKhsMVijE2ztm%2BqDb51AAAAAQAAAAAfgiesKh%2F3LmMmEsl2eFQfk9BSNWOIvB8NSUHGjDeANgAAAAJYVEFOTFAAAAAAAAAAAAAAfhe7mQVjhmwVKEimZUPqqo03IqGwxWKMTbO2b6oNvnUAAAAAC2NY6AAAAAEAAAAAQ7erE3VIVJC%2Fs3ZXRNYDUtTQZy7p%2BCurAxWjlSfnlhEAAAAGAAAAAlhUQU5MUAAAAAAAAAAAAAB%2BF7uZBWOGbBUoSKZlQ%2BqqjTciobDFYoxNs7Zvqg2%2BdX%2F%2F%2F%2F%2F%2F%2F%2F%2F%2FAAAAAQAAAAAfgiesKh%2F3LmMmEsl2eFQfk9BSNWOIvB8NSUHGjDeANgAAAAEAAAAAQ7erE3VIVJC%2Fs3ZXRNYDUtTQZy7p%2BCurAxWjlSfnlhEAAAACWFRBTkxQAAAAAAAAAAAAAH4Xu5kFY4ZsFShIpmVD6qqNNyKhsMVijE2ztm%2BqDb51AAAAAAtjWOgAAAAAAAAAAt95hOIAAABAMzMiBWeQNPTW47CLdVSLadV1ygtchbjVlqqNxbiSKs7hXt6V0wL4PaktRoLQUMNlvBokO63A%2FvoM76p6HsuwAcZ6dvwAAABAkzJT5d8PDJ738b5tKBEh0VsJFnugByKqWMV0HZ8crszBM8EGjfd9NCu%2Fud9GOwlO2DNvM3RGbIMGzJUy4FzBDA%3D%3D&type=TransactionEnvelope&network=test

Thank you!

**Comment by orbitlens** [comment] 2021-04-12 16:45
Looks like a bug. Let me check.

**Comment by orbitlens** [comment] 2021-04-12 18:52
I rolled out an update. Please check whether the issue is fixed on your side.

**Closed by orbitlens** 2021-04-12 18:52 UTC

**Comment by fsodano** [comment] 2021-04-13 01:20
Thanks mate, same issue. I triple-checked I was on the latest version.

![image](https://user-images.githubusercontent.com/844181/114482611-34116400-9c4a-11eb-9488-b1a5400dac85.png)


https://laboratory.stellar.org/#xdr-viewer?input=AAAAAgAAAABDt6sTdUhUkL%2BzdldE1gNS1NBnLun4K6sDFaOVJ%2BeWEQAAAyAABNboAAAAxQAAAAAAAAAAAAAACAAAAAEAAAAAH4InrCof9y5jJhLJdnhUH5PQUjVjiLwfDUlBxow3gDYAAAAGAAAAAlhUU0FSUwAAAAAAAAAAAAD%2BtBOh28Q8gg%2FXai72CIyzafowHwCf8bqYlAbcJULalAAI%2FA9nNjUBAAAAAQAAAABDt6sTdUhUkL%2BzdldE1gNS1NBnLun4K6sDFaOVJ%2BeWEQAAAAEAAAAAH4InrCof9y5jJhLJdnhUH5PQUjVjiLwfDUlBxow3gDYAAAACWFRTQVJTAAAAAAAAAAAAAP60E6HbxDyCD9dqLvYIjLNp%2BjAfAJ%2FxupiUBtwlQtqUAAAVVGxlFQAAAAABAAAAAB%2BCJ6wqH%2FcuYyYSyXZ4VB%2BT0FI1Y4i8Hw1JQcaMN4A2AAAABgAAAAJYVFNVU0RDAAAAAAAAAAAAYdNCcD5YFIcLTAcrVlZaeBsOllhsEuhB3f%2BWCpoXVNgAAA9Vb58UrAAAAAEAAAAAQ7erE3VIVJC%2Fs3ZXRNYDUtTQZy7p%2BCurAxWjlSfnlhEAAAABAAAAAB%2BCJ6wqH%2FcuYyYSyXZ4VB%2BT0FI1Y4i8Hw1JQcaMN4A2AAAAAlhUU1VTREMAAAAAAAAAAABh00JwPlgUhwtMBytWVlp4Gw6WWGwS6EHd%2F5YKmhdU2AAAACRnH2TVAAAAAQAAAAAfgiesKh%2F3LmMmEsl2eFQfk9BSNWOIvB8NSUHGjDeANgAAAAYAAAACWFRBTkxQAAAAAAAAAAAAAH4Xu5kFY4ZsFShIpmVD6qqNNyKhsMVijE2ztm%2BqDb51AAC7zJOLk74AAAABAAAAAH4Xu5kFY4ZsFShIpmVD6qqNNyKhsMVijE2ztm%2BqDb51AAAAAQAAAAAfgiesKh%2F3LmMmEsl2eFQfk9BSNWOIvB8NSUHGjDeANgAAAAJYVEFOTFAAAAAAAAAAAAAAfhe7mQVjhmwVKEimZUPqqo03IqGwxWKMTbO2b6oNvnUAAAG913n7xgAAAAEAAAAAQ7erE3VIVJC%2Fs3ZXRNYDUtTQZy7p%2BCurAxWjlSfnlhEAAAAGAAAAAlhUQU5MUAAAAAAAAAAAAAB%2BF7uZBWOGbBUoSKZlQ%2BqqjTciobDFYoxNs7Zvqg2%2BdX%2F%2F%2F%2F%2F%2F%2F%2F%2F%2FAAAAAQAAAAAfgiesKh%2F3LmMmEsl2eFQfk9BSNWOIvB8NSUHGjDeANgAAAAEAAAAAQ7erE3VIVJC%2Fs3ZXRNYDUtTQZy7p%2BCurAxWjlSfnlhEAAAACWFRBTkxQAAAAAAAAAAAAAH4Xu5kFY4ZsFShIpmVD6qqNNyKhsMVijE2ztm%2BqDb51AAABvdd5%2B8YAAAAAAAAAAt95hOIAAABAqxCrxIXaxORWCD9hGFbXYyvCCaXTKqu2m%2B9i0zKTwF0nqvhPozRiuvtvgcULauelUmkKcZhhqyTCOt3Ljy7kDsZ6dvwAAABACwTKLA0KagPYk6suQsh8yfsjZv6mdpHMJOexHP%2FZ%2F3sO3LD1I6BmO6TybNKvCYJ%2Fsf3PUengc%2FuFc6bvgBESBw%3D%3D&type=TransactionEnvelope&network=test

**Comment by orbitlens** [comment] 2021-04-14 18:26
I think we located the problem. Tested internally with very similar transaction, and now it works as expected.
Please check again with the latest version and let me know if the fix works for you.
